name: my_english_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 예시: 다른 패키지는 남기고, Firebase 관련만 일단 제거/주석 처리
  cupertino_icons: ^1.0.6
  file_picker: ^9.0.2
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  flutter_tts: ^4.2.2
  just_audio: ^0.9.35
  intl: ^0.20.2
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

# dependency_overrides:
#   firebase_core_web: 2.10.0
#   firebase_auth_web: 5.8.12
#   cloud_firestore_web: 3.12.4
#   firebase_storage_web: 3.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
